### ISSUE TITLE
Optimise for mobile

### ISSUE THREAD

**Issue by amankhoza** [KK578/comp3001#31] opened 2015-12-03 00:57 UTC
At the moment buttons, text etc. appears too small on mobile devices. Maybe find a way to scale up UI or something.

**Comment by KK578** [comment] 2015-12-03 20:36
Seems like it's mainly an issue with http://no2pollution.tk.

Most likely caused by viewport in iframe wrapper not being set. Fixed by changing from a frame wrapper to a URL Redirect to https://no2pollution.firebaseapp.com.

**Closed as completed by KK578** 2015-12-03 20:36 UTC
Labels: enhancement
